module.exports = {
  projects: [
    '<rootDir>/apps/01-bootstraping',
    '<rootDir>/apps/01-bootstraping-solution',
    '<rootDir>/apps/02-vue-material-bootstraping',
    '<rootDir>/apps/02-vue-material-bootstraping-solution',
    '<rootDir>/apps/03-first-components',
    '<rootDir>/apps/03-first-components-solution',
    '<rootDir>/apps/04-binding',
    '<rootDir>/apps/04-binding-solution',
    '<rootDir>/apps/05-event',
    '<rootDir>/apps/05-event-solution',
    '<rootDir>/apps/06-axios',
    '<rootDir>/apps/06-axios-solution',
    '<rootDir>/apps/07-routing',
    '<rootDir>/apps/07-routing-solution',
    '<rootDir>/apps/08-loop',
    '<rootDir>/apps/08-loop-solution',
    '<rootDir>/apps/09-props',
    '<rootDir>/apps/09-props-solution',
  ],
};
